### ISSUE TITLE
How to filter certain articles to display

### ISSUE THREAD

**Issue by mepearso** [mepearso/projectTwo#2]
So - I'm trying to show ALL of the articles for ONE particular category. I'm able to get all of the articles in my database but I'd like to only return the articles related to the category the user selects. 

I've tried using flow control and am now trying to use a filter method but I'm still not having any luck.. 

Here's where I'm at:

``` app.get("/articles/:category", function(req, res){
	var category = req.params.category;
	console.log("GET /articles/:category category=" + category);

	db.all("SELECT articles.*, category.categoryName, category.urlToken, authors.name FROM articles INNER JOIN category ON articles.category_id = category.id INNER JOIN authors ON articles.author_id = authors.id", function(error, rows){
		if(error){
			console.log(error);
		} else{
			console.log(rows);
			var html = fs.readFileSync("./views/viewAll.html", "utf8");
			var render = ejs.render(html, {articles: rows});
			res.send(render);
		}
	});
});
```

HTML CODE
```  <% articles.forEach(function(article){ %>
		<% if(article.categoryName==="Zodiacs"){ %>
				<a href="/articles/zodiacs/<%=article.id%>"><h3><%=article.title%></h3></a>
				<p><%=article.markdown%></p>
				<p>created by: <%=article.name%> | on: <%=article.createdTime%> | updated: <%=article.updatedTime%></p>
				<a href="/articles/<%=article.urlToken%>/<%=article.id%>/edit">edit this article</a><br>
				<img src="<%=article.imageURL%>">
		<% } else if (article.categoryName==="Stars"){%>
			<p>STARHIPSS</p>
		<%} else if(article.categoryName==="Planets"){%>
			<p>PLANETSHIPS</p>
		<%}%>
	<% }); %>
```

**Comment by mepearso** [comment]
When I try to go back to my index page.. I run into this error:

``` GET /articles/:category/:id category=zodiacs new
undefined
/Users/meganpearson/dev/wdi/projectTwo/node_modules/ejs/lib/ejs.js:236
  throw err;
        ^
TypeError: ejs:10
    8| 
    9| 	
 >> 10| 		<h3><%=article.title%></h3></a>
    11| 		<p><%=article.markdown%></p>
    12| 		<p>created by: <%=article.name%> | on: <%=article.createdTime%> | updated: <%=article.updatedTime%></p>
    13| 		<img src="<%=article.imageURL%>">

Cannot read property 'title' of undefined
    at eval (eval at <anonymous> (/Users/meganpearson/dev/wdi/projectTwo/node_modules/ejs/lib/ejs.js:460:12), <anonymous>:11:30)
    at returnedFn (/Users/meganpearson/dev/wdi/projectTwo/node_modules/ejs/lib/ejs.js:489:17)
    at Object.exports.render (/Users/meganpearson/dev/wdi/projectTwo/node_modules/ejs/lib/ejs.js:315:37)
    at Statement.<anonymous> (/Users/meganpearson/dev/wdi/projectTwo/app.js:65:21)
13 Aug 16:59:44 - [nodemon] app crashed - waiting for file changes before starting...

**Comment by mepearso** [comment]
THANKS!!
